{% set name = "pdm-backend" %}
{% set version = "2.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pdm_backend-{{ version }}.tar.gz
  sha256: dbd9047a7ac10d11a5227e97163b617ad5d665050476ff63867d971758200728

build:
  number: 1
  script: {{ PYTHON }} -m pip install ./ -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - python-build
    - pip
    - importlib-metadata >=3.6
  run:
    - python >={{ python_min }}
    - importlib-metadata >=3.6

test:
  source_files:
    - src
    - tests
  imports:
    - pdm.backend
  commands:
    - git config --global user.email "ci@github.com" && git config --global user.name "C I" && pytest tests
  requires:
    - pytest
    - setuptools
    - pytest-cov
    - pytest-xdist
    - git
    - gcc
    - python {{ python_min }}

about:
  home: https://pypi.org/project/pdm-backend/
  summary: The build backend used by PDM that supports latest packaging standards.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pdm-project/pdm-backend

extra:
  recipe-maintainers:
    - theAeon
    - xhochy
