{% set name = "pdm-backend" %}
{% set version = "2.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pdm_backend-{{ version }}.tar.gz
  sha256: a8616f628ec84353d7a0ba86b228dcf01bab5debc9e4d1a29e5311a52425d594

build:
  number: 1
  script: {{ PYTHON }} -m build && {{ PYTHON }} -m pip install dist/pdm_backend-{{ version }}-py3-none-any.whl
  noarch: python

requirements:
  host:
    - python >=3.8
    - python-build
    - pip
    - importlib-metadata >=3.6
  run:
    - python >=3.8
    - importlib-metadata >=3.6

test:
  source_files:
    - src
    - tests
  imports:
    - pdm.backend
  commands:
    - pytest tests
  requires:
    - pytest
    - setuptools
    - pytest-cov
    - pytest-xdist

about:
  home: https://pypi.org/project/pdm-backend/
  summary: The build backend used by PDM that supports latest packaging standards.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/pdm-project/pdm-backend

extra:
  recipe-maintainers:
    - theAeon
    - xhochy
